version: "3.4"

services:
  productapp:
    image: productapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      PGUSER: postgres
      PGPASSWORD: 1234
      PGDATABASE: aviosDB
      PGHOST: db
    command: >
      sh -c  "npx sequelize db:migrate && npx sequelize db:seed:all && npm run dev"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aviosDB
    ports:
      - 5430:5432
