version: "3.4"

services:
  productserver:
    image: productserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file: .env

    command: >
      sh -c  "npx sequelize db:migrate && npx sequelize db:seed:all && npm run dev"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5430:5432
    env_file: .env
